const wsTopProvidersTrending = {
  'abc': 'ABC News (Online)',
  'abovethelaw': 'Above The Law',
  'abridge': 'Abridge News',
  'ajplus': 'AJ+',
  'aljazeera': 'Al Jazeera',
  'allsides': 'AllSides',
  'allsides': 'AllSides Community',
  'alternet': 'AlterNet',
  'amgreatness': 'American Greatness',
  'americanthinker': 'American Thinker',
  'aquinas': 'Aquinas College Saint',
  'arcdigital': 'Arc Digital',
  'arkansasonline': 'Arkansas Democrat-Gazette',
  'apnews': 'Associated Press',
  'atlantablackstar': 'Atlanta Black Star',
  'ajc': 'Atlanta Journal-Constitution',
  'statesman': 'Austin American-Statesman',
  'axios': 'Axios',
  'azcentral': 'AZ Central',
  'babylonbee': 'Babylon Bee (Humor)',
  'barnstablepatriot': 'Barnstable Patriot',
  'bbc': 'BBC News',
  'bearingdrift': 'Bearing Drift',
  'bet': 'BET',
  'biblicalgenderroles': 'Biblical Gender Roles',
  'biblicalsexology': 'Biblical Sexology',
  'bizpacreview': 'Bizpac Review',
  'blackenterprize': 'Black Enterprise',
  'blockclubchicago': 'Block Club Chicago',
  'bloomberg': 'Bloomberg',
  'bluevirginia': 'Blue Virginia',
  'boingboing': 'Boing Boing',
  'bostonherald': 'Boston Herald',
  'bostonheraldeditorial': 'Boston Herald Editorial',
  'bostonreview': 'Boston Review',
  'bowlinggreendailynews': 'Bowling Green Daily News',
  'braverangels': 'Braver Angels',
  'breitbartnews': 'Breitbart News',
  'bridgemi': 'Bridgemi.com',
  'browngirlmagazine': 'Brown Girl Magazine',
  'bustle': 'Bustle',
  'buzzfeednews': 'BuzzFeed News',
  'byrondonalds': 'Byron Donalds',
  'cspan': 'C-SPAN',
  'calmatters': 'CalMatters',
  'calwatchdog': 'CalWatchdog',
  'care2': 'Care2',
  'cbn': 'CBN',
  'cbsnews': 'CBS News (Online)',
  'centermajormediasources': 'Center - Major Media Sources',
  'centerforpublicintegrity': 'Center for Public Integrity',
  'centreview': 'Centre View',
  'chicagocrusader': 'Chicago Crusader',
  'chicagodefender': 'Chicago Defender',
  'chicagosuntimes': 'Chicago Sun-Times',
  'chicagotribune': 'Chicago Tribune',
  'christiansciencemonitor': 'Christian Science Monitor',
  'christianitytoday': 'Christianity Today',
  'cityjournal': 'City Journal',
  'cnbc': 'CNBC',
  'cnn': 'CNN (Online News)',
  'cnn': 'CNN (Opinion)',
  'cnn': 'CNN Business',
  'cnsnews': 'CNSNews.com',
  'columbiajournalismreview': 'Columbia Journalism Review',
  'columbiamissourian': 'Columbia Missourian',
  'commentarymagazine': 'Commentary Magazine',
  'commondreams': 'Common Dreams',
  'concordmonitor': 'Concord Monitor',
  'conservativehq': 'Conservative HQ',
  'cookreport': 'Cook Report',
  'countercurrents': 'Counter Currents',
  'counterpointing': 'Counterpointing',
  'crowdpac': 'CrowdPAC',
  'cuindependent': 'CU Independent',
  'currentaffairs': 'Current Affairs',
  'dailybeast': 'Daily Beast',
  'dailybreeze': 'Daily Breeze',
  'dailycardinal': 'Daily Cardinal',
  'dailychela': 'Daily Chela',
  'dailycitizen': 'Daily Citizen',
  'dailykos': 'Daily Kos',
  'dailymail': 'Daily Mail',
  'dailynorthwestern': 'Daily Northwestern',
  'dailypress': 'Daily Press',
  'dailyprogress': 'Daily Progress',
  'dailytargum': 'Daily Targum',
  'defenseone': 'Defense One',
  'democracynow': 'Democracy Now',
  'desmoinesregister': 'Des Moines Register',
  'deseretnews': 'Deseret News',
  'desiringgod': 'Desiring God',
  'detroitfreepress': 'Detroit Free Press',
  'detroitnews': 'Detroit News',
  'deutschewelle': 'Deutsche Welle',
  'diplomaticcourier': 'Diplomatic Courier',
  'dividedwefall': 'Divided We Fall',
  'drudgereport': 'Drudge Report',
  'dukechronicle': 'Duke Chronicle',
  'eastbaytimes': 'East Bay Times',
  'educationweek': 'Education Week',
  'ellemagazine': 'Elle Magazine',
  'erraticus': 'Erraticus',
  'espn': 'ESPN.com',
  'esquire': 'Esquire',
  'estesparktrailgazette': 'Estes Park Trail Gazette',
  'eurekalert': 'Eurek Alert',
  'eviemagazine': 'Evie Magazine',
  'factcheckerblog': 'Fact Checker Blog',
  'fair': 'FAIR',
  'fallschurchnewspress': 'Falls Church News - Press',
  'financialtimes': 'Financial Times',
  'fiscaltimes': 'Fiscal Times',
  'fivethirtyeight': 'FiveThirtyEight',
  'forbes': 'Forbes',
  'foreignaffairs': 'Foreign Affairs',
  'foreignpolicy': 'Foreign Policy',
  'fortworthstartelegram': 'Fort Worth Star-Telegram',
  'fortune': 'Fortune',
  'foxbusiness': 'Fox Business',
  'fox': 'Fox News (Online News)',
  'fox': 'Fox News (Opinion)',
  'fox': 'Fox News Latino',
  'frontpagemagazine': 'FrontPage Magazine',
  'gizmodo': 'Gizmodo',
  'glaad': 'GLAAD',
  'golocalprovidence': 'GoLocal Providence',
  'google': 'Google News',
  'gq': 'GQ.com',
  'grist': 'Grist',
  'haaretz': 'Haaretz',
  'hamptonroadsmessanger': 'Hampton Roads Messanger',
  'harvardbusinessschool': 'Harvard Business School',
  'heavy': 'Heavy.com',
  'heralddemocrat': 'Herald Democrat',
  'hightimes': 'High Times',
  'hiplatina': 'Hip Latina',
  'honolulucivilbeat': 'Honolulu Civil Beat',
  'hotair': 'HotAir',
  'houstonchronicle': 'Houston Chronicle',
  'huffpost': 'HuffPost',
  'idahostatesman': 'Idaho Statesman',
  'inacow': 'Inacow',
  'independentjournalreview': 'Independent Journal Review',
  'indianadailystudent': 'Indiana Daily Student',
  'indyonline': 'Indy Online',
  'indyweek': 'Indy Week',
  'indystar': 'IndyStar',
  'infowars': 'InfoWars',
  'inlandvalleydailybulletin': 'Inland Valley Daily Bulletin',
  'insidephilanthropy': 'Inside Philanthropy',
  'insider': 'Insider',
  'intellectualconservative': 'Intellectual Conservative',
  'internationalbusinesstimes': 'International Business Times',
  'investors': 'Investor\'s Business Daily',
  'ivn': 'IVN',
  'jacobin': 'Jacobin',
  'jeffersonpublicradio': 'Jefferson Public Radio',
  'jezebel': 'Jezebel',
  'journalistsresource': 'Journalist\'s Resource',
  'jstordaily': 'JSTOR Daily',
  'jubileemedia': 'Jubilee Media',
  'judicialwatch': 'Judicial Watch',
  'justsecurity': 'Just Security',
  'justthenews': 'Just The News',
  'kalw': 'KALW.org',
  'katu': 'KATU',
  'kenoshanews': 'Kenosha News',
  'kqed': 'KQED',
  'ksl': 'KSL',
  'kwch': 'KWCH',
  'lasvegassun': 'Las Vegas Sun',
  'latinorebels': 'Latino Rebels',
  'lawandcrime': 'Law & Crime',
  'leafly': 'Leafly',
  'leesburgtoday': 'Leesburg Today',
  'leftmajormediasources': 'Left - Major Media Sources',
  'lgbtqnation': 'LGBTQ Nation',
  'lifehacker': 'Lifehacker',
  'listenfirstproject': 'Listen First Project',
  'liveactionnews': 'Live Action News',
  'livescience': 'Live Science',
  'longbeachpresstelegram': 'Long Beach Press-Telegram',
  'longmonttimescall': 'Longmont Times-Call',
  'losangelesdailynews': 'Los Angeles Daily News',
  'latimes': 'Los Angeles Times',
  'louisvillecourierjournal': 'Louisville Courier-Journal',
  'makingsense': 'Making Sense',
  'marijuanamoment': 'Marijuana Moment',
  'marketwatch': 'MarketWatch',
  'mashable': 'Mashable',
  'mcclatchydc': 'McClatchyDC',
  'mediamatters': 'Media Matters',
  'mediaresearchcenter': 'Media Research Center',
  'mediavillage': 'Media Village',
  'mediaite': 'Mediaite',
  'metroweekly': 'Metro Weekly',
  'miamiherald': 'Miami Herald',
  'michellemalkin': 'MichelleMalkin.com',
  'michigandaily': 'Michigan Daily',
  'militarytimes': 'Military Times',
  'misinformationreview': 'Misinformation Review',
  'mismatch': 'Mismatch.org',
  'mitnews': 'MIT News',
  'mitú': 'Mitú',
  'motherjones': 'Mother Jones',
  'msnbc': 'MSNBC',
  'mtvnewsonline': 'MTV News Online',
  'nationalgeographic': 'National Geographic',
  'nationaljournal': 'National Journal',
  'nationalreview': 'National Review',
  'nature': 'Nature.com',
  'nautilusquarterly': 'Nautilus Quarterly',
  'nbc': 'NBC News (Online)',
  'today': 'NBC Today Show',
  'newdiscourses': 'New Discourses',
  'newhampshireunionleader': 'New Hampshire Union Leader',
  'newrepublic': 'New Republic',
  'thedailynewsonline': 'New York Daily News',
  'newyorkmagazine': 'New York Magazine',
  'nypost': 'New York Post (News)',
  'nypost': 'New York Post (Opinion)',
  'nytimes': 'New York Times (News)',
  'nytimes': 'New York Times (Opinion)',
  'newsbusters': 'NewsBusters',
  'newsmax': 'Newsmax (News)',
  'newsmax': 'Newsmax - Opinion',
  'newsone': 'NewsOne',
  'newsweek': 'Newsweek',
  'newsy': 'Newsy',
  'newtrals': 'Newtrals',
  'niemanlab': 'Nieman Lab',
  'nmpolitics': 'NMPolitics.net',
  'npr': 'NPR (Online News)',
  'npr': 'NPR (Opinion)',
  'oan': 'One America News Network (OAN)',
  'orangecountyregister': 'Orange County Register',
  'our': 'Our.News',
  'outkickthecoverage': 'Outkick the Coverage',
  'pacificstandard': 'Pacific Standard',
  'palmspringsdesertsun': 'Palm Springs Desert Sun',
  'pasadenastarnews': 'Pasadena Star-News',
  'patch': 'Patch.com',
  'pbsnewshour': 'PBS NewsHour',
  'peacockpanache': 'Peacock Panache',
  'phys': 'Phys.org',
  'pinknews': 'PinkNews',
  'pittsburghposgazette': 'Pittsburgh Post-Gazette',
  'pjmedia': 'PJ Media',
  'politico': 'Politico',
  'politicususa': 'PoliticusUSA',
  'portlandpressherald': 'Portland Press Herald',
  'poynter': 'Poynter',
  'pri': 'PRI (Public Radio International)',
  'progressivevoicesofiowa': 'Progressive Voices of Iowa',
  'projectveritas': 'Project Veritas',
  'propublica': 'ProPublica',
  'psychologytoday': 'Psychology Today',
  'pxwnews': 'PXW News',
  'quartz': 'Quartz',
  'quillette': 'Quillette',
  'rasmussenreports': 'Rasmussen Reports',
  'rawstory': 'Raw Story',
  'realclearpolitics': 'RealClearPolitics',
  'reason': 'Reason',
  'recordjournal': 'Record Journal',
  'redracinghorses': 'Red Racing Horses',
  'redlandsdailyfacts': 'Redlands Daily Facts',
  'redstate': 'RedState',
  'refinery29': 'Refinery29',
  'reuters': 'Reuters',
  'revolvernews': 'Revolver News',
  'richmondtimesdispatch': 'Richmond Times Dispatch',
  'rightmajormediasources': 'Right - Major Media Sources',
  'rightsidenews': 'Right Side News',
  'rightwingnews': 'Right Wing News',
  'rollcall': 'Roll Call',
  'rollingstone': 'RollingStone.com',
  'salon': 'Salon',
  'sanantonioexpressnews': 'San Antonio Express-News',
  'sanbernardinosun': 'San Bernardino Sun',
  'sandiegouniontribune': 'San Diego Union-Tribune',
  'sanfranciscochronicle': 'San Francisco Chronicle',
  'sangabrielvalleytribune': 'San Gabriel Valley Tribune',
  'sanjosemercurynews': 'San Jose Mercury News',
  'sciencedaily': 'Science Daily',
  'scientificamerican': 'Scientific American',
  'scotusblog': 'SCOTUSblog',
  'scriberrmedianews': 'Scriberr Media - News',
  'scriberrmediaopinion': 'Scriberr Media - Opinion/Editorial',
  'sfweekly': 'SF Weekly',
  'sfgate': 'SFGate',
  'skyhidailynews': 'Sky-Hi Daily News',
  'slate': 'Slate',
  'smerconish': 'Smerconish',
  'smithsonianmagazine': 'Smithsonian Magazine',
  'socialistalternative': 'Socialist Alternative',
  'socialistproject': 'Socialist Project/The Bullet',
  'southchinamorningpost': 'South China Morning Post',
  'spectatorusa': 'Spectator USA',
  'spiked': 'Spiked',
  'splinter': 'Splinter',
  'spokesmanreview': 'Spokesman Review',
  'stlouispostdispatch': 'St. Louis Post-Dispatch',
  'startribune': 'Star Tribune',
  'stat': 'STAT',
  'statejournal': 'State Journal',
  'storycorps': 'StoryCorps',
  'studentsforlife': 'Students For Life',
  'subverse': 'Subverse',
  'suspendbeliefpodcast': 'Suspend Belief Podcast',
  'tabletmag': 'Tablet Mag',
  'tallahasseedemocrat': 'Tallahassee Democrat',
  'tampabaytimes': 'Tampa Bay Times',
  'techxplore': 'Tech Xplore',
  'techcrunch': 'TechCrunch',
  'teenvogue': 'Teen Vogue',
  'theadvocate': 'The Advocate',
  'theadvocatemessenger': 'The Advocate-Messenger',
  'theamericanconservative': 'The American Conservative',
  'theamericanmind': 'The American Mind',
  'theamericanspectator': 'The American Spectator',
  'theappeal': 'The Appeal',
  'theatlantic': 'The Atlantic',
  'thebellows': 'The Bellows',
  'thebostonglobe': 'The Boston Globe',
  'thebulwark': 'The Bulwark',
  'thecadizrecord': 'The Cadiz Record',
  'thecanyoncountyzephyr': 'The Canyon County Zephyr',
  'thecentersquaremichigan': 'The Center Square - Michigan',
  'thechristianpost': 'The Christian Post',
  'thecollegefix': 'The College Fix',
  'thecoloradosun': 'The Colorado Sun',
  'thecolumbusdispatch': 'The Columbus Dispatch',
  'thecommercialappeal': 'The Commercial Appeal',
  'theconversation': 'The Conversation',
  'thecourierjournal': 'The Courier-Journal',
  'thedailycaller': 'The Daily Caller',
  'thedailydot': 'The Daily Dot',
  'thedailysignal': 'The Daily Signal',
  'thedailywire': 'The Daily Wire',
  'thedallasmorningnews': 'The Dallas Morning News',
  'thedelawarecountydailytimes': 'The Delaware County Daily Times',
  'thedispatch': 'The Dispatch',
  'theeconomist': 'The Economist',
  'theepochtimes': 'The Epoch Times',
  'thefederalist': 'The Federalist',
  'theflipside': 'The Flip Side',
  'thefulcrum': 'The Fulcrum',
  'thegatewaypundit': 'The Gateway Pundit',
  'theglobeandmail': 'The Globe and Mail',
  'theguardian': 'The Guardian',
  'thehill': 'The Hill',
  'thehollywoodreporter': 'The Hollywood Reporter',
  'theimaginativeconservative': 'The Imaginative Conservative',
  'theindependent': 'The Independent',
  'theintercept': 'The Intercept',
  'thejapantimes': 'The Japan Times',
  'thejerusalempost': 'The Jerusalem Post',
  'thejuggernaut': 'The Juggernaut',
  'thejustice': 'The Justice',
  'thekoreaherald': 'The Korea Herald',
  'thelibertarianrepublic': 'The Libertarian Republic',
  'thelincolnproject': 'The Lincoln Project',
  'thelufkindailynews': 'The Lufkin Daily News',
  'themaneater': 'The Maneater',
  'themarkup': 'The Markup',
  'themarshallproject': 'The Marshall Project',
  'thenation': 'The Nation',
  'thenationalpulse': 'The National Pulse',
  'newyorker': 'The New Yorker',
  'observer': 'The Observer (New York)',
  'theonion': 'The Onion (Humor)',
  'theoracle': 'The Oracle',
  'theoregonian': 'The Oregonian',
  'thephiladelphiainquirer': 'The Philadelphia Inquirer',
  'theplebeian': 'The Plebeian',
  'thepolicetribune': 'The Police Tribune',
  'thepostmillennial': 'The Post Millennial',
  'thepressenterprise': 'The Press-Enterprise',
  'theredandblack': 'The Red and Black',
  'thereliablebias': 'The Reliable Bias',
  'therepublican': 'The Republican',
  'theresurgent': 'The Resurgent',
  'theroot': 'The Root',
  'thesacramentobee': 'The Sacramento Bee',
  'thesaturdayeveningpost': 'The Saturday Evening Post',
  'theseattletimes': 'The Seattle Times',
  'thesouthafrican': 'The South African',
  'thetelegraphuk': 'The Telegraph - UK',
  'thetennesseean': 'The Tennesseean',
  'thetexan': 'The Texan',
  'thetexasobserver': 'The Texas Observer',
  'thetexastribune': 'The Texas Tribune',
  'thetimespicayune': 'The Times-Picayune',
  'theverge': 'The Verge',
  'theweeknews': 'The Week - News',
  'theweeknews': 'The Week - Opinion',
  'theweeklystandard': 'The Weekly Standard',
  'thewesternjournal': 'The Western Journal',
  'theblaze': 'TheBlaze.com',
  'thinkprogress': 'ThinkProgress',
  'time': 'Time Magazine',
  'townhall': 'Townhall',
  'trains': 'Trains.com',
  'truthdig': 'Truthdig',
  'truthout': 'TruthOut',
  'usnews': 'U.S. News & World Report',
  'univision': 'Univision',
  'upworthy': 'Upworthy',
  'usatoday': 'USA TODAY',
  'vanityfair': 'Vanity Fair',
  'variety': 'Variety',
  'vice': 'Vice',
  'virginiamercury': 'Virginia Mercury',
  'voiceofamerica': 'Voice of America',
  'volante': 'Volante',
  'vox': 'Vox',
  'vtdigger': 'VT Digger',
  'wakeuptopolitics': 'Wake Up to Politics',
  'wsj': 'Wall Street Journal (News)',
  'wsj': 'Wall Street Journal (Opinion)',
  'wandtv': 'WANDTV',
  'washingtonexaminer': 'Washington Examiner',
  'washingtonfreebeacon': 'Washington Free Beacon',
  'washingtonmonthly': 'Washington Monthly',
  'washingtonpost': 'Washington Post',
  'washingtontimes': 'Washington Times',
  'watchdog': 'Watchdog.org',
  'wfae': 'WFAE',
  'wgbh': 'WGBH',
  'wgn': 'WGN',
  'whatfingernews': 'Whatfinger News',
  'whittierdailynews': 'Whittier Daily News',
  'wired': 'Wired',
  'wisconsingazette': 'Wisconsin Gazette',
  'wnd': 'WND.com',
  'yahoo': 'Yahoo News',
  'yahoo': 'Yahoo! The 360',
  'yesmagazine': 'Yes! Magazine',
  'zerohedge': 'ZeroHedge',
}
//
// for (let i = 0; i < Object.keys(wsTopProvidersTrending).length; i++) {
//   console.log(wsTopProvidersTrending[Object.keys(wsTopProvidersTrending)[i]]);
// }


module.exports = wsTopProvidersTrending;